# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: cardano-node
    type: github
    endpoint: raycrawfordGitHubServiceConnection
    name: reachtheworld/cardano-node
    ref: refs/tags/1.29.0

steps:
- checkout: cardano-node
  path: cardano-node

- task: UniversalPackages@0
  displayName: 'Download libsodium artifact'
  inputs:
    command: download
    downloadDirectory: '$(Build.SourcesDirectory)'
    vstsFeed: 'cardano-stake/libsodium'
    vstsFeedPackage: 'libsodium'
    vstsPackageVersion: '*'

- script: |
    sudo tar xvf $(Build.SourcesDirectory)/libsodium.tar -C /
    sudo find /usr/local/lib -name libsodium* -type f -exec chmod 644 {} \;
    ls -alF /usr/local/lib/
    ls -alF /usr/local/lib/pkgconfig/
    echo -n LD_LIBRARY_PATH = 
    echo $LD_LIBRARY_PATH
    export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
    export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
  displayName: 'Install libsodium'

- script: |
    echo $LD_LIBRARY_PATH
    ghc --version
    cabal --version
    sudo apt-get update -y
    sudo apt-get install automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf -y