# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: cardano-node
    type: github
    name: reachtheworld/cardano-node
    ref: tree/1.27.0
    endpoint: raycrawfordGitHubServiceConnection

steps:
#- checkout: libsodium
#  path: libsodium
- task: UniversalPackages@0
  displayName: 'Download libsodium artifact'
  inputs:
    command: download
    downloadDirectory: '$(Build.SourcesDirectory)'
    vstsFeed: 'cardano-stake/libsodium'
    vstsFeedPackage: 'libsodium'
    vstsPackageVersion: '*'

- script: |
    sudo tar xvf $(Build.SourcesDirectory)/libsodium.tar -C /
    ls -alF /usr/local/lib/
    ls -alF /usr/local/lib/pkgconfig/
  displayName: 'test'
